name: "Smart Release Please"
description: "Manages version control for RC releases on 'next' and stable releases on 'main'."

inputs:
  token:
    description: "GitHub Token (PAT) for authentication"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v6 
      with:
        fetch-depth: 0
        token: ${{ inputs.token }}

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'

    - name: Configure Git Identity
      shell: bash
      run: |
        git config user.name "mapcolonies[bot]"
        git config user.email "devops[bot]@mapcolonies.com"

    - name: Calculate Next Version
      id: calc_rc
      shell: bash
      run: python3 "${{ github.action_path }}/rc_align.py"

    # ============================================================
    # MAIN BRANCH ONLY: Update manifest for stable releases
    # ============================================================
    - name: Update Release Manifest (Main Branch)
      if: (github.ref_name == 'main' || github.ref_name == 'master') && steps.calc_rc.outputs.next_version != ''
      shell: bash
      run: |
        TARGET_VER="${{ steps.calc_rc.outputs.next_version }}"
        echo "Updating manifest to version: $TARGET_VER"
        echo "{\".\": \"$TARGET_VER\"}" > .release-please-manifest.json
        
        git add .release-please-manifest.json
        
        if ! git diff --staged --quiet; then
          git commit -m "chore: update manifest to $TARGET_VER for stable release"
          git push "https://x-access-token:${{ inputs.token }}@github.com/${{ github.repository }}.git" ${{ github.ref_name }}
        else
          echo "No changes to manifest, skipping commit"
        fi

    # ============================================================
    # VERSION ENFORCEMENT: Add Release-As footer when needed
    # Skip if: already has Release-As, is a release commit, or is a merge from main
    # ============================================================
    - name: Enforce Version with Release-As Footer
      if: >-
        ${{ 
          steps.calc_rc.outputs.next_version != '' &&
          !contains(github.event.head_commit.message, 'Release-As:') &&
          !(startsWith(github.event.head_commit.message, 'chore(') && contains(github.event.head_commit.message, '): release')) &&
          !(contains(github.event.head_commit.message, 'Merge branch') && contains(github.event.head_commit.message, 'main'))
        }}
      shell: bash
      run: |
        TARGET_VER="${{ steps.calc_rc.outputs.next_version }}"
        LAST_MSG=$(git log -1 --pretty=%B)
        
        # Prevent infinite loop: check if footer already exists
        if [[ "$LAST_MSG" == *"Release-As: $TARGET_VER"* ]]; then
          echo "✓ Release-As footer already present, skipping"
          exit 0
        fi

        # Add Release-As footer to guide release-please
        echo "Injecting Release-As: $TARGET_VER footer"
        git commit --allow-empty -m "chore: enforce correct rc version" -m "Release-As: $TARGET_VER"
        git push "https://x-access-token:${{ inputs.token }}@github.com/${{ github.repository }}.git" ${{ github.ref_name }}

        # Signal to skip release-please in this run (it will run on the next trigger)
        echo "SKIP_RELEASE=true" >> $GITHUB_ENV

    # ============================================================
    # CLEANUP: Close stale release PRs to force regeneration
    # ============================================================
    - name: Close Stale Release PRs
      if: env.SKIP_RELEASE != 'true' && !contains(github.ref, 'release-please--branches')
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        echo "Checking for stale release PRs on branch '${{ github.ref_name }}'..."
        
        PR_DATA=$(gh pr list \
          --base "${{ github.ref_name }}" \
          --label "autorelease: pending" \
          --json number,state \
          --jq '.[0]')

        if [ -z "$PR_DATA" ] || [ "$PR_DATA" == "null" ]; then
          echo "✓ No open release PRs found"
          exit 0
        fi

        PR_NUMBER=$(echo "$PR_DATA" | jq -r '.number')
        PR_STATE=$(echo "$PR_DATA" | jq -r '.state')
        
        if [ "$PR_STATE" == "OPEN" ]; then
          echo "Closing stale release PR #$PR_NUMBER to force regeneration..."
          gh pr close "$PR_NUMBER" --delete-branch
        else
          echo "Found PR #$PR_NUMBER but it's already $PR_STATE, skipping"
        fi

    - name: Run Release Please
      if: env.SKIP_RELEASE != 'true'
      uses: googleapis/release-please-action@v4
      with:
        token: ${{ inputs.token }}
        target-branch: ${{ github.ref_name }}
        config-file: release-please-config.${{ github.ref_name }}.json
